### ISSUE TITLE
Please make it mirror blueprints too!

### ISSUE THREAD

**Issue by lunivore** [christoph-frick/factorio-blueprint-tools#1]
I was looking for tools to mirror my blueprints and found the link you'd added to the forum. Please could you add the mirroring to the online version? Thank you very much!

**Comment by christoph-frick** [comment]
I have added that (mirrors on the Y axxis for now).  But i have not tested it much other than mirroring some belts. I'd also only expect it to work properly with symmetric entities.

**Comment by christoph-frick** [comment]
Added support for horizontal or vertical mirroring

**Comment by lunivore** [comment]
Thank you very much! :D Pretty sure Reddit would like to know too... /r/factorio
