### ISSUE TITLE
Support for landfilling all/recursive blueprints in a book

### ISSUE THREAD

**Issue by Henriquelay** [christoph-frick/factorio-blueprint-tools#12]
It returns a blueprint for a single landfill tile.

> _I am willing to help in this project, but right now I can't just open a pr. If you accept help, assign me to this issue and I will fix it and close when I can, and then continue working on the tool._

**Comment by christoph-frick** [comment]
@Henriquelay Thank you for your suggestion. It works now for my simple tests - it is a bit more iffy for the "grid aligned" blueprints since 0.18.x, but I'll address that at some point in the future.

**Comment by Henriquelay** [comment]
It doesn't landfill books within books -- They get converted to a blueprint with a landfill tile, just like when I opened the issue. Tested in 1.0.0.

**Comment by christoph-frick** [comment]
@Henriquelay Thanks for the heads up. Seems like I have not your catched up with all the new 1.0 stuff
