### ISSUE TITLE
Tile offset when mirroring

### ISSUE THREAD

**Issue by RickHutten** [christoph-frick/factorio-blueprint-tools#14]
The following blueprint has an issue when you mirror it. It offsets the tiles by 1.

> 0eNq1nc1y47gVRl+lS2srxQuAANGLbKYqeYKsprpcskzbrJElhZK6pjPlN8gy+7xiHiGUPbbkNinec9m9abck4uKHOPi5+AD8MbtZHept26z3s89/zJrlZr2bff71j9muuV8vVsfv9t+29ezzrNnXj7Or2XrxePx0aBfr5vA4vzvUq/myXq1mT1ezZn1b/z77LE9frmb1et/sm/rF2POHb9frw+NN3XYPvJlpNzeb7abdd4a3m10XYLM+RtkZ8Vezb7PP8/z0dPUhvHsLX/++bevdbr7vkrM7Gprf1Ksea/P0l/LFYPefLqW3TVsvX36PPRF4HkFEEQQeQYkiKHkEHkUQeQQBRZB4BA5FUPEIBEWQP0Rw6ABp79tN93cgimI4hqtXEjeH/fawn/XEKAXPU4HyJIJjYGSIM5RaqSi1Zj1UaJx21poIp71iEXDaM4uA0y6wXnHcheEunHdhvEvmMbBG13G+hbW67sT33WK3nzfrXd3uu18+Gh6GzvUZdlrDp766azl6u/8TsMvup7a5O9zXl+yE5wR2yWu252OXbbtZdkXYrO+7wMfhze4Ycret69v54+b2sKrn7piZviQEdW78WG5KXW78T8xNVOemGMtNUuWm+ImZqVQpKH9iCrK2OONIafpClZf8Q/LSkf/uK38cyfclSt1E5LHsOVX25CdWfe/V7d0YyP7UJuinI6JpO/2pidA0m24gfVGfvpKlL+ktR2a50lsOzHLWW/bIcig0b8uPvK0g+vQ5lj6ntyzMsldbLphhgBa0rEGrGHtXerKGCzT0GdaDNVwHev0Peq4CM6zHyiPDZaE2HJlhPWglM+wUVascqVqlHqnEUqdHqmKGSz0MBbOsxywzw0nxpvLYm9IjJcKSp2dKWDMQ9VAJwzWKokhlrBOMJ4R2h5vdfvEcuKebkmczvcPV6PmwrNA0ztEy3tNZLg3jqUL1Wk4IjXvVTqPAwuKMjCeqburFsvfFuXcF3j909wND93gC7q5ZdRVsPt6Df8hIV8FeAr8sVLyuYHxY53C+nD196UtFJiVaKEp00FGZCj4KUtW3JLwk5xOKsuovyuT4MEqXP48N6+wGfbm5IcNxcrGV2ilsGExDn9lTU7Hb18dVvod6d2EYV/Q34SnpzJQjZipVT5CG+4GUR5ujPKE1qgreG6jmAJVww05lWO+Rjciu2qXy1sGohhTVibbV5r7Z7ZvlS2Wabxe7XfO1PvqBvja3F3Mg/dWrKrk3wGnml1XkDgxdtUjcsC7FFXcP6Axn7tFQGc6GflFVxlmwP0OXYMcTrDPssb9AZzfgDlRnV+N98ZfRzRG7MnRpS9iTobNbYX+Dzm7GDhKVXSkK7IJQGhbsglAadtwFobTssQtCaTjwOb7Scsn9EkrLkXsPlJbTUFff1v88dH97+/i3gnldJnp+9Pri6LppN+v5drXYH9edlt3Ubf9c43sH2lJUE0YgbzXtJXU3i+f1/N5oMh/xeU1/Jmf6IMVkNb1L8LlthahGhK82vUTUDc337WZ1fVM/LL42m/b41LJpl4dmf12vFzer+vq22R3/zj7fLVa7+urt57Ze3F4/LNa310cjXZK6t75vD2dPvH7/8mg3pq+P04XnSNcv2Xse8svxn/u2rtfn+sXm9liTQ1c5nnqz7Ljbxvd3aiKeF5/XCbgCHzgqLZekdvl3tselbWcaJNIm8CbhsOtme4ft/KPE9a2FKAcaCNE4kufFEFf9parTM7xmtHy/RL4+LFf1on3JRFufrZT3xpWRduK7uH7bfF209e/zet02y4fHzsDryvyMzqblTOnUTfaXv83Hl1CGUDqTNGlEFD8zU06dqTyWKc+kEz8zV0GdK/Fj2VIpHd46+nLIzKmt6Drm+vFm1dX4+eNi+dCsjznpW0H402Tql5ic69x74lNx/zYCKFWd9ZmQ6YLR14oSVQMrB4YW1ZDl3mbKm4YW0aRy9oaxxVBV8R/1xrvtqtkPOMLeUt1ra8K+gVL1/ojGyF8o40tjrO632zdDd03b9ZfKzSDPiyTPxruG4NhPpuOHx+2iXeyPccz++vzzwFju/UCtbyj33WivbyxXoLGcyNBYzqOxTBivzhfk52eO9uGa99rkJQ2LycJiNTzMv8RixVlMQ/xkPjRVKvALzo3SslgGvdX5oHe4alikWspke+6CrAZem0WdpUxlif2OlapvPVNsXRitjFRXoM4KLHXVdyOq0dXF9zRMW0+UwD2JunyVBc1XtORrYKVeSu5vVObL0XxVP/J9AY2YFCxjgWZMih/6xkocv/uhJRu5V1ZZsvq2Q1jjUeLGQ8IPfWegE3+dvEih24VWoGlWVpVXBJOJN9PaBDvuyVWm2qBq0yY68Dmi1rRB2KY1bdjdoDVtWGrXmq74uFRr2rDBIQ+MdIjyTFgyz7RnitmPFBqThuX1wZzzLQ3ajBtGzVrTZPI62FqqXDEpYsWBNhMJj/11TWeqsGFtkokW1I2X+/DEEKjNYLMB5GawrTvTm42Xjp9UKyuPM6GrO1XA4g1t6ZR40qW1HLHlrDNM3EzlpOpe4Zmb8n1mbFhZ6pmrZrSWiccpTeIoG4Q0urqTDXNWbfkErNHRWib9ap5S4YGoTWAnBXRtArtsIG0ThzjNpGcVmVLpHdC7SSCV3hWEXPHqCvSl+6JZ/XnW1ofx+J87Jaqn04rxZr1s6339nP2h5xN8PsLnS/h8gM97+LyDzwt7vmCPQ+sw8bBsYNHDNwsrDqyXsNpn+JrUrzVACgOkMEAKA6QwQAoDpDBACgOkMDAKA6MwMAoDozAwCsP3FD4s/rVob+evoeZtc/+wvxQ2TgibhsOu6ruLQSt70GwPqmfYQ4Y9ZNhDhj1k2EOGPWTYQ4Y9ZNgzhj1j2DOGPWPYM4b9BIb9BIa9nWFvZ9jbGfaQYQcZdpBhBxl2kGEHGXaQYQcZdpBhxxh2jGHHGHaMYccYdmMMD9dqN4bwWNBkD1rZg2Z7UD3BAgkWSLBAggUSLJBggQQLJFggwcIIFkawMIKFESyMYLETLHaCxU6wjBF8oeuXMYRHw+oZLiDDxQeG9WVSfOAZhy0nhA0TwvoJYR0sW2HPw1cNrcPEe/Z4YI9PePsTKt2Eum7jv5jAf8H4zwz/bKc/2+HPdvazHf1sJz8z8DPjPiPsM6I+I+gzYj4j5DPyYGfkwM7If52R+zoj73VmuFYM18qOa2XHtbLjWtlxrey4VgzXiuFaIVwrhGuFcK0QrhXCtUK4VgjXCuFaIVwrhGvFcE0M12THNdlxTXZckx3XZMc1MVwTwzUhXBPCNSFcE8I1IVwTwjUhXBPCNSFcE8I1MVwjwzXacY12XKMd12jHNdpxjQzXyHCNCNeIcI0I14hwjQjXiHCNCNeIcI0I14hwjQxXKKcq7biWdlxLO66lHdfSjisUYUENFpNgMQUWE2Ax/RWTXzH1FRNfMe0Vk14x5RUUXkHdVbDjGuy4BjuuwY5rsOMK1VpQrMW0WkyqxZRaTKjFdFoB4RoQrgHhGhCuAeEKNVZQYuXtuHo7rt6Oq7fj6u24QmEW1GUxWRZTZTFRFtNkMUmWR7h6hKtHuHqEq0e4QjkVVFM5O67Ojquz4+rsuDo7rlCDBSVYTIHFBFhMf8XkV0x95RCuDuHqEK4O4eoQrlQ7BWUXE1QXE0QXEzQXEyQXExQXUHAB9RZMbsHUFkxs8T2uQCDwPbs0aGkPGu1Bkz0oYyyz16usDUxlZddY2RVWdn2VXV1l11YxZRXTVSFVFdJUIUVVYWa8MCNemAkvzIAXZr4LgndB6GYiKtaX27tye09u78jt/bi9G2e9OOvEUR+OunDUg9s7cHv/be++7b23vfNGfTfqulnPzebV9mm1fVZtn1Tb59T2KTWbUbMJNZpPo+k0mk07M9zODLczw+3McDsz3GgijubhbBrOfNx2F7fdw213cNv923b3NvNuM+c28m0j1zbybHsz3N4Mt30Lsn0DsjfDjZziyCfOXOJsvdm+3GxfbbYvNtvXmu1LzWylmS00o3VmtMyMVpmDGe5ghtt+Roj9hJBghhstUKP1abY8zbRfdumXXfllF37ZdV922RdTfTHRF9J8IckXUnyVZrhLM9ylGe7SDHdphhuJxZBWjEnFmA7bLsO2q7DtImy7BtsuwWYKbCbARvprJL9G6utohjua4Y5muKMZ7miGGwm3kW6bybbZnij7lij7jij7hij7fij7dii2G4pthkJ7odBWKLQTKpnhTma4kxnuZIY7meFGm6jQHiq2hYrtT7ZvT7bvTrZvTrbvTbZvTWY7k9nGZLQvGW1LRruSKzPclRnuygx3ZYa7MsONNjSj/cxsOzM7K8R+VIj9pBD7QSH2c0Lsx4SwU0LYISHojBB0RAg6ISSb4c5muLMZ7myGO5vhRoeLoLNF2NEi8CCwCeeATTgGbMIpYBMOAZtwBhg8AgyeAMYOAGPnf7Hjv8SuVhO7XE3sejWxC9bErlgTJFkTpFmDJ3/Bwztlgmxtgm5tgnBtgnJtgnQNategeI2p15h8jenXJgjYJijYJkjYJmjYJojYmIqNydiYjg0ety12JZvYpWxi17KJXcwmdjUbPKQbntHNjuhmJ3SzA7rFrmkTu6hN7Ko2scvaxK5rEyRsE6Rsg6dzwysyxC5uE7u6TezyNrHr28QucIMXa8B7Ndi1GuxWDXaphthlbmLXuU24a2PCVRtil7oJ0roJErvB+zTgtVZi17uJXfAmdsWb2CVvYte8wcuw4F1Y7CosdhMWuwhL7Mo3sUvfJtyPNeF6LLGr3wTJ3wTp3+AdWPAySbFL4MSugRO7CE7sKjixy+DgFZTwBkp2ASW7f5JdPyl2MZzY1XBil8OJXQ8ndkEcu7mSXVx58d7KL1ezZl8/dt/drA71tm3Wx3tpV4ubetV997///uffn/7RLtbN4fHT3w716tMv9Wr16de/L9ou+Kdfvt3U7ZdPx6e6QF/rdvccq6skpJBTTFLEMj49/R8qpiak

**Comment by christoph-frick** [comment]
@RickHutten Thanks for the report with an example

Mirroring now moves the result back into the original bounding box, which also fixes #13; Only adjusting the tiles for negative result coords did not work as it moved the tiles one to far to the left. I call shenanigans on the new "non-centered" blueprints Wube introduced shortly before 1.0.
