### ISSUE TITLE
Can't mirror of this string

### ISSUE THREAD

**Issue by Fatmice** [christoph-frick/factorio-blueprint-tools#18]
Vertical or horizontal mirror of this string will not import

`0eNqdnO1OIkkUhu+lf8OkTn2XF7A3sZlsUIlDgmgQJ2sm3PuCMiz2ltvvwy9lBp5UdVX1eXw97a/hdv26fN6uNrvh5tfwslk8z3dP84ft6v74+u/hJvnZ8Hb44vazYXX3tHkZbv48vHH1sFmsj2/ZvT0vh5thtVs+DrNhs3g8vtouVuvh+IHN/fLAsP332bDc7Fa71fLj8+8v3v7avD7eLreHN5w/efe6/bm8n78DZsPz08vhM0+b01hCfB/LPB4Hc7/aLu8+/jPtZ/9B+jPyZXegPfzYfQVNJ2jYdzABY6yHiWyCIU9PMNGRhdYbWdZG5usJEj+PzHeQRR6ZnaDlMzR0oBVPt/Sm2+BC+OmFMPdp38/vfixWm/nphHTm/O33AOO3JNANTzz1Jm5em/m89meee0z5dMzDiRqmt49FmWqAKp8XAs3y4gCofH4SgMrnpwBoU6FNh3onLxRYKS8fIwNL5eUqY2CtvHysDCyWl4+VkdWSj5UnqyWfK09Wq8Ba5wRmxcUuTBc73/BNv28vTr+Vnobn2+fhlR7238N0pB6K3e7p+X/WxkbXcXYYzeLj+2Ho8f3nivpVLfXxXEttXEt79SoEVv19na7PIV5Z/Z1S/QO3vK5/BlHz5vZ76iMDtR60MKUYX87uElWqFOMN2zuloVGlUKjRQaWQoAaVQoJ6qBQSNEClkKARKoUETVQpJGqmSiFRC1UKiVqpUkjURpVCoSZHlUKiGlUKieqZUoxvq11moEoxHmlPKVKklcR384KUuFKkaaVIGSmFL1ApUqFK4YuiFKlCpYhCstOuUwqfFaXIDm+EbpKSjSqFn1aKDFOK8eXsLVHGKcV4w/ZOacYphUSlKYUEpSmFBKUphQSlKYUEpSmFAi04pZCoOKWQqDilkKg4pZCoOKWQqDilkKg4pZCoMKUY31a7TJxSjEfaU4qCUwrfjabrFSmFTStFZSmFD1ApKk4pfFCUotKUQvhtWL0ypfBeUYqKUwrfjasqTSmsTitFLfruSufd1QNV6CZOWOuG3cSmj3tz2E0UqlE3UaCeuokCDdRNFGikbqJAE3UTBZqxmyjUgt1EoVbsJgq1YTcRqOYclhMJa9hOJKzHeiJhA/OT8T26D41YUGxaUMzxwtS99ZvLuIhY65MKlh0r07JjriLbsQZtx1yjumNN0R27tn/CqtY/AZuLLCtQ3F70xXawQJUnTiuPkRaKdN5kXVJi0jO+ev0Vz9R6xkegexOxQrVHw1boPRq1QfGRqHrzRCJUg+qjUT10H40aqPxo2EjtR8Mmqj8aNlP/0bCF+o+GrdR/NGyj/iNhL3oqNP+JCtSo/5jQM2mBl6l+GQiBF5R+G2KI3H+C4D8XnRKS/yTqPxctFKr/JMl/QrnSf7T+0QB/Q2VKy2toVFucoC3R8V3WDZIsGtQWpdtV76I4a4vU7hqwtkjYSLVFoiaqLRI1U22RqIVqi0StVFskasPaIjU9O6wtEtawtkhYj7VFwgasLRI2Ym2RsAlri4SFD3qYU6D4UQ8Tul8tVV4H+rlNatg2hP5Xu+ihkGSDNsDaRXOFKhtSB6xlf6VsSO2qlmmcIbSZWuZpRj9syTDMqMoFxVlGU54rwVGGRKVJhgSlQYYCLTTHkKA0xpCgNMWQoDjEkKg4w5CoOMKQqDjBkKg4wJCoOL+QqDi+UKgVphdZYeLwQuhXterxXb+fXdSAHUBoWLWLlgrFAWjDql00VYgKIDWsWs3XGYDUXGq10K5QQQAq98F++FQbEwChu9RAs0Xo7q7+k5VGBUCieigAEjRAAZCgEQqABE1QACRohgIgQQsVAIlaqQBI1EYFIClPATsqABLVqABIVE8FQKIGKgASlf8w1Y1YveMPgghNm96xB0Fo06Z3+EEQqWnTu8oKn1D3vGs8B+muleFg/QuOUU5/7xh2u0M9/z77+CszNxd/s2Y2rBe3y/Xh3/5Yr47b5Ody+/KxE6rFElvJxVxOeb//B6VYFTA=`

**Comment by christoph-frick** [comment]
@Fatmice What do you mean by "will not import"?  I tried above string, mirrored vertically, and was able to paste into factorio and place it (note that the trainstops will be wrong, but this is currently expected (because usually mirroring would also imply to switch the directions)). If you think this related to the wrong placing of the trainstations/signals, please try again without those.

**Comment by Fatmice** [comment]
"Will not import" means that when I paste the mirrored string into Factorio, the game literally freezes for a minute without showing a blueprint. I don't know if Linux version of the game matters...I've tried to import in editor mode or single player mode.  If I do it during multiplayer mode, I get dropped from the game.

I've mirrored for more complicated strings before with your website....it's just this one that failed to import and I don't know why.

**Comment by Fatmice** [comment]
Okay, I figure out why. Part of this string some how messes with the copy/paste buffer on Linux, leading to a null buffer or a completely messed up buffer.

**Comment by christoph-frick** [comment]
@Fatmice I tried also on linux but in a modded save game (krastorio+SE). Since the trainstops are misplaced, could you try without them and see if that triggers the slowdown?

**Comment by christoph-frick** [comment]
Ah well you figured it out. Cheers.
