### ISSUE TITLE
Mirroring curved rails result in the wrong orientating

### ISSUE THREAD

**Issue by LeonSkills** [christoph-frick/factorio-blueprint-tools#2]
@christoph-frick 
Thanks for adding the mirror tool! Was mirroring some rail blueprints and noticed the curved rails aren't rotated properly

Simple circle (Not that that needs mirroring, but simplest example)
`0eNqV1OFugyAQAOB3ud80KVgReZVlWaySjkTRADYzhncfStq0jkX5RQ69zwvcOcO1HcWgpbLAZ5B1rwzwjxmMvKmqXfbsNAjgIK3oAIGquiXSlWzBIZCqET/AsftEIJSVVoqQvwbTlxq7q9D+hWdmPeq7aE4rgGDojc/p1fIh75xyBJNfMPZ2I7Wow0Pq0B+SHCOzuJhFxOwpGuux27f9r0wWUPZuFhHzctSkURJHyPzgWWIcyHyfpMfI8gFGiCKtquy9qEtEZClFbbw84pWJ10v3SXxO6utyv18wTmnrDUhiIEnrQLqdEz/Z6+zzl18FgrvQJowmKwhhuDwXxLlf68xrSw==`

Results in a beautiful but useless star
`0eJyV1NuOgyAQANB/mWdMBKsiv7LZbKxOuiSKBrBZY/z3RW2a1mWjPHKZw22GCa7NgL2WyoKYQFadMiA+JjDypspm6bNjjyBAWmyBgCrbpaVL2cBMQKoaf0DQ+ZMAKiutxC1+bYxfamivqN2EZ2Q16DvW0QoQ6DvjYjq1LOSclMAIIqLU0bXUWG1jbCZ/RHZOjBI/mXrI5Eka67Tbt/0H5ZvJ30nqIS9nySjzmrnHTM+dnNJNTI/F7ORdFl4x9oh50B6Td/DiAXnQFndg4gGLsMfOjkUahyR5cZw89GTVPHJ8J2Y+kQXmY7avGlfn608gXj4OAnfUZluU54xxWsQ5m+dfTrFv5g==`

**Comment by christoph-frick** [comment]
Thanks for reporting. Curved rails now have their special treatment.
