### ISSUE TITLE
Landfill Sparse ignores Tiles

### ISSUE THREAD

**Issue by Ranakastrasz** [christoph-frick/factorio-blueprint-tools#20]
`Tested it, looks like it works great, however, it doesn't include other tiles, like Brick or Concrete. Say If I want to make a city-grid, which in water sets up bridges in effect.`

https://pastebin.com/H9EELRsz

My expectation was that I would be able to place the blueprint, build the landfill, and then place the entire blueprint in the exact same splot. The tool is expected to either place landfill underneath the concrete, or else replace the concrete with landfill. Instead, the concrete was removed, and landfill was placed beneath each entity.
So, partially successful.

**Comment by christoph-frick** [comment]
Do you know whether this is supported in Factorio at all? Can some tile
and a land-fill time exist on the same space?

I'd expect no, but I can try.  One way out of this could be to create
a blueprint book for a single blueprint, where the blueprint gets added
and another blueprint with just the landfill too.

I think i'll try the later first as this would also help debugging
landfill in general and makes placing the blueprint easier.

BTW: your pastebin link has expired - no need to provide another though
(I understand the problem).  For future reference please use a simple
blueprint showing the problem and just paste the string into the ticket.

**Comment by Ranakastrasz** [comment]
Really? I thought I set it to 1 year.

I have no idea either. That said, If you just replace all tiles with landfill in addition to the rest, it would be fine.

**Comment by Ranakastrasz** [comment]
I confirm that you cannot have two types of tiles on a single.... Tile.... Square thinggy.
I request that in Landfill Sparse mode, all tiles of any type should be replaced with Landfill.

**Comment by christoph-frick** [comment]
There now is another setting for landfilling: remove existing tiles,
replace tiles by landfill too, or create blueprint (first blueprint is
only the landfill (over entities and tiles) and the second one is the
original blueprint)
