### ISSUE TITLE
Avoid adding landfill under walls

### ISSUE THREAD

**Issue by EmileSonneveld** [christoph-frick/factorio-blueprint-tools#32]
Water is the best barrier agains biters.
In an outpost it would be beneficial to keep water instead of putting landfill for walls.
Would it be possible to keep have an option to not add landfill under walls?

**Comment by christoph-frick** [comment]
I have added this by providing a multi-select for entities to not put landfill
under; by default `stone-wall` and `gate` are available and selected; in all
theory I could open this up by providing any known entity as an option (and
have some sane defaults like the walls) -- but the entity information available
right now is "everything with a bounding box" (which is full with stuff like
"burned-tree-42").
