### ISSUE TITLE
Fill with landfill

### ISSUE THREAD

**Issue by dunkfordyce** [christoph-frick/factorio-blueprint-tools#4]
Could you make an option to put landfill under all structures? That would be very useful for building on water in an efficient manner.

**Comment by christoph-frick** [comment]
I tried that (https://github.com/christoph-frick/factorio-blueprint-tools/tree/landfill) and it does not work. 

It's possible to add landfill as the "tiles" of the blueprint, buf if you try to place the blueprint over water, the game will state "can not build on water".  If you shift-click to build only, the entities on land are placed and the landfill itself - but no ghosts on water are placed.

If you aware of a way to make it work, feel free to suggest/reopen - but I think it can't be done (best thing doable would be having blueprints with landfill larger than the brushsize)

**Comment by christoph-frick** [comment]
There is a mod that battles with the same problem https://mods.factorio.com/mod/LandfillEverything - so there seems to be at least some need for this feature.  I think I'll just merge the branch anyway and see what happens...

**Comment by dunkfordyce** [comment]
Thanks for trying anyway!

**Comment by christoph-frick** [comment]
The "best what's possible" function is online

**Comment by christoph-frick** [comment]
For the records: https://forums.factorio.com/viewtopic.php?f=6&t=66688 (lengthy discussions about the problem)
