### ISSUE TITLE
New feature: Breaking blueprints up

### ISSUE THREAD

**Issue by wrygiel** [christoph-frick/factorio-blueprint-tools#6]
I designed an enormous blueprint in an a map editor. Now it's [impossible to place it without breaking achievements](https://www.reddit.com/r/factorio/comments/6qvtaa/how_to_position_a_large_blueprint_that_go_outside/). A feature to break up large blueprints into smaller tiles might be useful for such cases :)

**Comment by christoph-frick** [comment]
I added this (menu item "split").  For now it just deals with entities (no tiles etc). It creates a blueprint book named like the blueprint and creates the "tiles" according to the configured size. I don't know what are good starting tile settings as i assume factorios zoom depends on resolution - for me 64 gave a nice to deal with result. So far i only tested with a "simple" conveyor grid with ~3.8k items that splits 2x2.

**Comment by wrygiel** [comment]
Thanks!

I think there's still a small bug in the implementation which prevents me from using it. All the blueprints in the book are oriented based on the original size of the blueprint. So, even after they are cut, they still end up off screen. [Example](https://i.imgur.com/QA5FfPf.jpg).

(I would guess that there's some "overall size" attribute which should be reset to 64, but isn't?)

**Comment by christoph-frick** [comment]
The center of your blueprint is really the center.  So yes, this is wrong and each "tile" should be adjusted to -64/2.

**Comment by christoph-frick** [comment]
The centering seems fixed now.  But blueprints with train tracks might have problems - the tracks must be placed on a grid or else Factorio shifts them.  See #7

**Comment by christoph-frick** [comment]
@wrygiel #7 is now fixed.  If you still find problems, please provide a the failing example and open a new ticket.
