### ISSUE TITLE
Storage Tank does not mirror correctly

### ISSUE THREAD

**Issue by haynesgt** [christoph-frick/factorio-blueprint-tools#8]
e.g.

0eNqN0NsKgzAMBuB3yXUFW0FZX2WM4SFImKalrWMiffdVhbHNXeymkDb9Ev4FmmFC64gD6AWoNexBnxfw1HM9rHdhtggaKOAIArge18oH4+oes1DzDaIA4g4foGW8CEAOFAh3ZyvmK09jgy41/BYEWOPTJ8PrxATlAuZ0Jrkjh+3+oqI4gOoFWrJJM1nvzMTdkVQbmclPs/xhFn+b2Y7K7z1TClte+i1eAXd0fmuoilyeSiWLqozxCRCbgGg=

becomes

0eJyN0NsKgzAMBuB3yXUFW0FZX2WM4SFImKalrWMiffdVhbHNXeymkDb9Ev4FmmFC64gD6AWoNexBnxfw1HM9rHdhtggaKOAIArge18oH4+oes1DzDaIA4g4foGW8CEAOFAh3ZyvmK09jgy41/BYEWOPTJ8PrxATlAuZ0Jrkjh+3+UkZxANULtGSTZrLemYm7I5mpzczkJ6p+oMXf6G7K7z1TClte+i1eAXd0fmuoilyeSiWLqozxCQWngGw=

but it should be

0eNqNkN0KgzAMhd8l1xVsBWV9lTGGP0HCNC1tHRPpu68qjDG92FVIcvLlJAs0w4TWEQfQC1Br2IO+LuCp53pYa2G2CBoo4AgCuB7XzAfj6h6zUPMDogDiDl+gZbwJQA4UCHfOlsx3nsYGXRJ8CJZsGjdZ78zEXSJb49OY4XVnQmVKwJyCTPSOHLZ7T0VxgKpzWwdkvhHzeIIo/va12/pxVa53bx/SXw8V8ETnN0FV5PJSKllUZYxv++17yw==

**Comment by christoph-frick** [comment]
Thanks reporting this and providing test cases.  The problem is fixed - storage tanks must be rotated instead of mirrored.
